# Generated by Django 6.0.4 on 2026-05-05 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total rent for the apartment', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
