# Generated by Django 6.0.4 on 2026-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househelp', '0003_remove_househelp_bio_househelp_area_househelp_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelp',
            name='expected_salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
